[package]
name        = "tmkms"
description = "Tendermint Key Management System"
version     = "0.10.0-alpha3"
authors     = ["Tony Arcieri <tony@iqlusion.io>", "Ismail Khoffi <Ismail.Khoffi@gmail.com>"]
license     = "Apache-2.0"
repository  = "https://github.com/iqlusioninc/tmkms/"
readme      = "README.md"
categories  = ["cryptography"]
keywords    = ["cosmos", "ed25519", "kms", "key-management", "yubihsm"]
edition     = "2018"

[dependencies]
abscissa_core = "0.5"
abscissa_tokio = { version = "0.5", optional = true }
bytes = "0.5"
chacha20poly1305 = "0.7"
chrono = "0.4"
ed25519-dalek = "1"
getrandom = "0.1"
gumdrop = "0.7"
hkd32 = { version = "0.5", default-features = false, features = ["mnemonic"] }
hkdf = "0.10.0"
hyper = { version = "0.13", optional = true }
hyper-rustls = { version = "0.21", optional = true }
k256 = { version = "0.5", features = ["ecdsa", "sha256"] }
ledger = { version = "0.2", optional = true }
merlin = "2"
once_cell = "1.4"
prost = "0.6"
prost-amino = "0.6"
prost-amino-derive = "0.6"
prost-derive = "0.6"
prost-types = "0.6"
rand_core = { version = "0.5", features = ["std"] }
rpassword = { version = "5", optional = true }
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"
sha2 = "0.9"
signature = { version = "1.2", features = ["std"] }
stdtx = { version = "0.3", optional = true }
subtle = "2"
subtle-encoding = { version = "0.5", features = ["bech32-preview"] }
tempfile = "3"
tendermint = { version = "0.17.0-rc1", features = ["secp256k1"] }
tendermint-rpc = { version = "0.17.0-rc1", optional = true, features = ["http-client"] }
tendermint-proto = "0.17.0-rc1"
thiserror = "1"
wait-timeout = "0.2"
x25519-dalek = "1.1"
yubihsm = { version = "0.35", features = ["secp256k1", "setup", "usb"], optional = true }
zeroize = "1"

[dev-dependencies]
abscissa_core = { version = "0.5", features = ["testing"] }
byteorder = "1"
rand = "0.7"

[features]
softsign = []
tx-signer = ["abscissa_tokio", "hyper", "hyper-rustls", "stdtx", "tendermint-rpc"]
yubihsm-mock = ["yubihsm/mockhsm"]
yubihsm-server = ["yubihsm/http-server", "rpassword"]

# Enable integer overflow checks in release builds for security reasons
[profile.release]
overflow-checks = true

[package.metadata.docs.rs]
all-features = true
