[package]
name        = "tmkms"
description = "Tendermint Key Management System"
version     = "0.8.0-alpha1" # Also update html_root_url in lib.rs when bumping this
authors     = ["Tony Arcieri <tony@iqlusion.io>", "Ismail Khoffi <Ismail.Khoffi@gmail.com>"]
license     = "Apache-2.0"
repository  = "https://github.com/iqlusioninc/tmkms/"
readme      = "README.md"
categories  = ["cryptography"]
keywords    = ["cosmos", "ed25519", "kms", "key-management", "yubihsm"]
edition     = "2018"

[dependencies]
abscissa_core = "0.5"
abscissa_tokio = "0.5"
bytes = "0.5"
chacha20poly1305 = "0.5"
chrono = "0.4"
getrandom = "0.1"
gumdrop = "0.7"
hkd32 = { version = "0.4", default-features = false, features = ["mnemonic"] }
hkdf = "0.9.0-alpha.0"
hyper = { version = "0.13", optional = true }
k256 = "0.3"
merlin = "2"
once_cell = "1.3"
prost-amino = "0.5"
prost-amino-derive = "0.5"
rand = "0.7"
rpassword = { version = "4", optional = true }
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"
sha2 = "0.9"
signatory = { version = "0.20", features = ["ecdsa", "ed25519", "encoding"] }
signatory-dalek = "0.20"
signatory-secp256k1 = "0.20"
signatory-ledger-tm = { version = "0.20", optional = true }
stdtx = { version = "0.2", optional = true }
subtle = "2"
subtle-encoding = { version = "0.5", features = ["bech32-preview"] }
tempfile = "3"
tendermint = "0.14"
tendermint-rpc = { version = "0.14.0", optional = true, features = ["client"] }
thiserror = "1"
wait-timeout = "0.2"
x25519-dalek = "0.6"
yubihsm = { version = "0.34", features = ["secp256k1", "setup", "usb"], optional = true }
zeroize = "1"

[dev-dependencies]
tempfile = "3"

[dev-dependencies.abscissa_core]
version = "0.5"
features = ["testing"]

[features]
default = ["tx-signer"]
ledgertm = ["signatory-ledger-tm"]
softsign = []
tx-signer = ["hyper", "stdtx", "tendermint-rpc"]
yubihsm-mock = ["yubihsm/mockhsm"]
yubihsm-server = ["yubihsm/http-server", "rpassword"]

# Enable integer overflow checks in release builds for security reasons
[profile.release]
overflow-checks = true

[package.metadata.docs.rs]
all-features = true
